import game, {
  initGameData,
  startGame,
  selectFigure,
  updateBoard,
  addStrikedFigure,
  setShah,
  endGame,
  addMessage,
  userLeave,
  plusTime,
  drawPurposeReceived,
  sendDrawPurpose,
  surrenderAction,
  acceptDrawPurpose,
  rejectDrawPurpose,
  purposeRejected,
  prevFrame,
  nextFrame,
  setMoves,
  clearHistory,
} from './game.slice';

export {
  initGameData,
  startGame,
  selectFigure,
  updateBoard,
  addStrikedFigure,
  setShah,
  endGame,
  addMessage,
  userLeave,
  plusTime,
  drawPurposeReceived,
  purposeRejected,
  sendDrawPurpose,
  acceptDrawPurpose,
  rejectDrawPurpose,
  prevFrame,
  surrenderAction,
  nextFrame,
  clearHistory,
  setMoves,
};

export default game;
